//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class aidatAy
    {
        public int id { get; set; }
        public Nullable<int> aidatId { get; set; }
        public Nullable<int> ay { get; set; }
    
        public virtual aidatlar aidatlar { get; set; }
    }
}
