//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class anket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anket()
        {
            this.AnketiGorenlers = new HashSet<AnketiGorenler>();
            this.anketSorularis = new HashSet<anketSorulari>();
        }
    
        public int id { get; set; }
        public string anketKonusu { get; set; }
        public Nullable<int> yoneticiId { get; set; }
    
        public virtual yonetici yonetici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketiGorenler> AnketiGorenlers { get; set; }
        public virtual anketSonuclari anketSonuclari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anketSorulari> anketSorularis { get; set; }
    }
}
