//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apartman()
        {
            this.guvenliks = new HashSet<guvenlik>();
            this.uyes = new HashSet<uye>();
        }
    
        public int id { get; set; }
        public string apartmanAdi { get; set; }
        public string apartmanBlok { get; set; }
        public Nullable<int> katSayisi { get; set; }
        public Nullable<int> apartmanYoneticisi { get; set; }
        public Nullable<int> daireSayisi { get; set; }
        public Nullable<int> aidat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guvenlik> guvenliks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uye> uyes { get; set; }
    }
}
