//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class daireSakini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public daireSakini()
        {
            this.aracbilgisis = new HashSet<aracbilgisi>();
        }
    
        public int id { get; set; }
        public Nullable<int> uyeId { get; set; }
        public string ad { get; set; }
        public string soyAd { get; set; }
        public Nullable<int> yas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aracbilgisi> aracbilgisis { get; set; }
        public virtual uye uye { get; set; }
    }
}
