//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class duyurular
    {
        public int id { get; set; }
        public string duyurAdi { get; set; }
        public string duyuruKonusu { get; set; }
        public Nullable<int> yoneticiId { get; set; }
    
        public virtual yonetici yonetici { get; set; }
    }
}
