//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class gelenMesaj
    {
        public int id { get; set; }
        public Nullable<int> gidenId { get; set; }
        public string mesaj { get; set; }
        public Nullable<int> mesajId { get; set; }
        public Nullable<int> gelenId { get; set; }
        public Nullable<int> oncelik { get; set; }
    
        public virtual mesaj mesaj1 { get; set; }
    }
}
