//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyAd { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string cinsiyet { get; set; }
        public string mailAdresi { get; set; }
        public string telefon { get; set; }
        public string medeniDurum { get; set; }
        public string sifre { get; set; }
        public string tipAdi { get; set; }
        public string kAdi { get; set; }
    
        public virtual resimler resimler { get; set; }
        public virtual uye uye { get; set; }
        public virtual yonetici yonetici { get; set; }
    }
}
