//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class resimler
    {
        public int id { get; set; }
        public string resimAd { get; set; }
        public byte[] resim { get; set; }
    
        public virtual kullanici kullanici { get; set; }
    }
}
