//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Yönetim_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uye()
        {
            this.daireSakinis = new HashSet<daireSakini>();
        }
    
        public int Id { get; set; }
        public Nullable<int> apartmanId { get; set; }
        public Nullable<int> kat { get; set; }
        public Nullable<int> daireNo { get; set; }
        public Nullable<int> aracSayisi { get; set; }
        public Nullable<int> aracId { get; set; }
    
        public virtual aidatlar aidatlar { get; set; }
        public virtual apartman apartman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daireSakini> daireSakinis { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual mesaj mesaj { get; set; }
    }
}
